export type City =
  | 'Waterloo'
  | 'Toronto'
  | 'London'
  | 'Reading'
  | 'Oxford'
  | 'Maidenhead'
  | 'Milan'
  | 'Lisbon'
  | 'Edinburgh'
  | 'Cardiff'
  | 'Geneva'
  | 'Caen'
  | 'New York'
  | 'Everett'
  | 'Kitchener'
  | 'Providence'
  | 'Hong Kong'
  | 'Mississauga'
  | 'Windsor'
  | 'Bracknell'

  export type Category =
  | 'Thai'
  | 'Chinese'
  | 'Vietnamese'
  | 'Indian'
  | 'Japanese'
  | 'Korean'
  | 'Lebanese'
  | 'Pizza'
  | 'Seafood'
  | 'Steakhouse'
  | 'Burgers'
  | 'British'
  | 'Italian'
  | 'Brunch'
  | 'Coffee'
  | 'BBQ'
  | 'Hotpot'
  | 'Middle Eastern'
  | 'French'
  | 'Canadian'
  | 'Asian Fusion'
  | 'Nepalese'
  | 'Scottish'
  | 'Portuguese'
  | 'Mediterranean'
  | 'International'
  | 'Swiss'
  | 'Bar & Grill'
  | 'Other'
export type Price = '$' | '$$' | '$$$' | '$$$$'

export type Restaurant = {
  id: string
  name: string
  headline: string
  city: City
  neighbourhood?: string
  category: Category
  price: Price
  tags: string[]
  defaultRating: number
  lat: number
  lng: number
}
export const restaurants: Restaurant[] = [
  {
    id: 'lunch-lady-of-saigon-toronto',
    name: 'Lunch Lady of Saigon',
    headline: 'Best Vietnamese restaurant in Toronto',
    city: 'Toronto',
    neighbourhood: 'Little Italy',
    category: 'Vietnamese',
    price: '$$',
    tags: ['vietnamese', 'pho', 'best vietnamese restaurant in toronto'],
    defaultRating: 5.0,
    lat: 43.64639,
    lng: -79.41921,
  },
  {
    id: 'janet-lynns-bistro-waterloo',
    name: "Janet Lynn's Bistro",
    headline: 'Best Canadian restaurant in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Canadian',
    price: '$$$$',
    tags: ['canadian', 'fine dining', 'best canadian restaurant in waterloo'],
    defaultRating: 5.0,
    lat: 43.4643,
    lng: -80.5204,
  },
  {
    id: 'dishoom-permit-room-oxford',
    name: 'Dishoom Permit Room',
    headline: 'Great curry spot in Oxford',
    city: 'Oxford',
    neighbourhood: 'City Centre',
    category: 'Indian',
    price: '$$$',
    tags: ['indian', 'curry', 'oxford'],
    defaultRating: 5.0,
    lat: 51.7520674,
    lng: -1.2598278,
  },
  {
    id: 'tamasha-waterloo',
    name: 'Tamasha',
    headline: 'Best Indian restaurant in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Indian',
    price: '$$$',
    tags: ['indian', 'curry', 'best indian restaurant in waterloo'],
    defaultRating: 5.0,
    lat: 43.4500073,
    lng: -80.4899544,
  },
  {
    id: 'favorites-thai-bbq-toronto',
    name: 'Favorites Thai BBQ',
    headline: 'Insane lamb chops',
    city: 'Toronto',
    neighbourhood: 'Chinatown',
    category: 'Thai',
    price: '$$$$',
    tags: ['thai', 'bbq', 'lamb chops'],
    defaultRating: 5.0,
    lat: 43.64775,
    lng: -79.41989,
  },
  {
    id: 'lobster-burger-bar-toronto',
    name: 'Lobster Burger Bar',
    headline: 'Lobster absolutely slapped',
    city: 'Toronto',
    neighbourhood: 'King West',
    category: 'Seafood',
    price: '$$$',
    tags: ['seafood', 'lobster', 'burgers'],
    defaultRating: 5.0,
    lat: 43.6473853,
    lng: -79.3867874,
  },
  {
    id: 'jumbo-lobster-restaurant-toronto',
    name: 'Jumbo Lobster Restaurant',
    headline: 'Giant lobster tower moment',
    city: 'Toronto',
    neighbourhood: 'North York',
    category: 'Seafood',
    price: '$$$$',
    tags: ['lobster', 'seafood', 'tower'],
    defaultRating: 5.0,
    lat: 43.84797,
    lng: -79.38214,
  },
  {
    id: 'bombay-story-maidenhead',
    name: 'Bombay Story',
    headline: 'Best Indian restaurant in Berkshire',
    city: 'Maidenhead',
    neighbourhood: 'Town Centre',
    category: 'Indian',
    price: '$$',
    tags: ['indian', 'curry', 'best indian restaurant in berkshire'],
    defaultRating: 5.0,
    lat: 51.5237007,
    lng: -0.7172264,
  },
  {
    id: 'fallow-london',
    name: 'Fallow',
    headline: 'Innovative modern British plates',
    city: 'London',
    neighbourhood: 'St James’s',
    category: 'British',
    price: '$$$',
    tags: ['british', 'modern', 'innovative'],
    defaultRating: 5.0,
    lat: 51.5094184,
    lng: -0.1327361,
  },
  {
    id: 'hawkmoor-seven-dials',
    name: 'Hawksmoor Seven Dials',
    headline: 'Top-tier British beef',
    city: 'London',
    neighbourhood: 'Seven Dials',
    category: 'Steakhouse',
    price: '$$$$',
    tags: ['steak', 'british', 'beef'],
    defaultRating: 4.8,
    lat: 51.51357,
    lng: -0.12578,
  },
  {
    id: 'moon-place-cantonese-toronto',
    name: 'Moon Palace Cantonese Cuisine',
    headline: 'Scallop siu mai is elite',
    city: 'Toronto',
    neighbourhood: 'Scarborough',
    category: 'Chinese',
    price: '$$',
    tags: ['dim sum', 'cantonese', 'siu mai'],
    defaultRating: 4.8,
    lat: 43.65639,
    lng: -79.38235,
  },
  {
    id: 'honest-burgers-reading',
    name: 'Honest Burgers',
    headline: 'Juicy, properly cooked burger',
    city: 'Reading',
    neighbourhood: 'Town Centre',
    category: 'Burgers',
    price: '$$',
    tags: ['burgers', 'juicy', 'reading'],
    defaultRating: 4.7,
    lat: 51.4552905,
    lng: -0.9693146,
  },
  {
    id: 'rodneys-oyster-house-toronto',
    name: "Rodney's Oyster House",
    headline: 'Seafood go-to',
    city: 'Toronto',
    neighbourhood: 'King West',
    category: 'Seafood',
    price: '$$$',
    tags: ['oysters', 'seafood', 'raw bar'],
    defaultRating: 4.7,
    lat: 43.6450,
    lng: -79.3956,
  },
  {
    id: 'fishmans-lobster-clubhouse-toronto',
    name: "Fishman's Lobster Clubhouse",
    headline: 'Another absurd lobster tower',
    city: 'Toronto',
    neighbourhood: 'Scarborough',
    category: 'Seafood',
    price: '$$$$',
    tags: ['lobster', 'seafood', 'tower'],
    defaultRating: 4.7,
    lat: 43.7731,
    lng: -79.2607,
  },
  {
    id: 'amal-toronto',
    name: 'Amal',
    headline: 'Best Lebanese restaurant in Toronto',
    city: 'Toronto',
    neighbourhood: 'Yorkville',
    category: 'Lebanese',
    price: '$$$',
    tags: ['lebanese', 'mezze', 'best lebanese restaurant in toronto'],
    defaultRating: 4.8,
    lat: 43.668672,
    lng: -79.3925218,
  },
  {
    id: 'bone-daddies-soho',
    name: 'Bone Daddies',
    headline: 'Best ramen restaurant in London',
    city: 'London',
    neighbourhood: 'Soho',
    category: 'Japanese',
    price: '$$',
    tags: ['ramen', 'japanese', 'best ramen restaurant in london'],
    defaultRating: 4.7,
    lat: 51.5128173,
    lng: -0.1338703,
  },
  {
    id: 'bhel-puri-house-reading',
    name: 'Bhel Puri House',
    headline: 'Elite Indian street food',
    city: 'Reading',
    neighbourhood: 'Town Centre',
    category: 'Indian',
    price: '$',
    tags: ['indian', 'street food', 'chaat'],
    defaultRating: 4.7,
    lat: 51.4547089,
    lng: -0.9703917,
  },
  {
    id: 'china-bowl-waterloo',
    name: 'The China Bowl',
    headline: 'Your Waterloo Chinese food default',
    city: 'Waterloo',
    neighbourhood: 'University',
    category: 'Chinese',
    price: '$$',
    tags: ['chinese', 'waterloo', 'go-to'],
    defaultRating: 4.6,
    lat: 43.47721,
    lng: -80.52485,
  },
  {
    id: 'royal-china-chuan-london',
    name: 'Royal China Chuan',
    headline: 'XLB are to die for',
    city: 'London',
    neighbourhood: 'City',
    category: 'Chinese',
    price: '$$$',
    tags: ['xiaolongbao', 'dim sum', 'shanghai'],
    defaultRating: 4.7,
    lat: 51.51168,
    lng: -0.13157,
  },
  {
    id: 'knead-neapolitan-pizza-berkshire',
    name: 'Knead Neapolitan Pizza',
    headline: 'Best pizza restaurant in Berkshire',
    city: 'Reading',
    neighbourhood: 'Town Centre',
    category: 'Pizza',
    price: '$$',
    tags: ['pizza', 'neapolitan', 'best pizza restaurant in berkshire'],
    defaultRating: 4.7,
    lat: 51.52164,
    lng: -0.71799,
  },
  {
    id: 'momo-waterloo',
    name: 'MoMo',
    headline: 'Solid Nepalese momos',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Nepalese',
    price: '$',
    tags: ['momo', 'dumplings', 'waterloo'],
    defaultRating: 4.5,
    lat: 43.4730414,
    lng: -80.5353937,
  },
  {
    id: 'pizza-nova-waterloo',
    name: 'Pizza Nova',
    headline: 'Nice owner, reliable slice',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Pizza',
    price: '$',
    tags: ['pizza', 'waterloo', 'late night'],
    defaultRating: 4.6,
    lat: 43.4723602,
    lng: -80.5361385,
  },
  {
    id: 'bao-sandwich-bar-toronto',
    name: 'Bao Sandwich Bar',
    headline: 'Duck poutine goes hard',
    city: 'Waterloo',
    neighbourhood: 'University',
    category: 'Chinese',
    price: '$$',
    tags: ['bao', 'duck poutine', 'fusion'],
    defaultRating: 4.5,
    lat: 43.47663,
    lng: -80.53007,
  },
  {
    id: 'empress-of-india-waterloo',
    name: 'Empress of India',
    headline: '2nd best Indian restaurant in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Indian',
    price: '$$',
    tags: ['indian', 'curry', 'second best indian restaurant in waterloo'],
    defaultRating: 4.7,
    lat: 43.4645226,
    lng: -80.5218112,
  },
  {
    id: 'one-square-edinburgh',
    name: 'One Square',
    headline: 'Lamb is very tasty',
    city: 'Edinburgh',
    neighbourhood: 'Old Town',
    category: 'Scottish',
    price: '$$$',
    tags: ['lamb', 'scottish', 'fine dining'],
    defaultRating: 4.4,
    lat: 55.9491879,
    lng: -3.1904163,
  },
  {
    id: 'soi-thaifoon-waterloo',
    name: 'SOI Thaifoon',
    headline: 'Best Thai restaurant in Waterloo (get the green curry)',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Thai',
    price: '$$',
    tags: ['thai', 'green curry', 'best thai restaurant in waterloo'],
    defaultRating: 4.6,
    lat: 43.4518733,
    lng: -80.4953554,
  },
  {
    id: 'the-bull-inn-berkshire',
    name: 'The Bull Inn',
    headline: 'Mussels are a must-have',
    city: 'Reading',
    neighbourhood: 'Arborfield',
    category: 'British',
    price: '$$$',
    tags: ['mussels', 'pub food', 'british'],
    defaultRating: 4.7,
    lat: 51.39773,
    lng: -0.90707,
  },
  {
    id: 'storia-maidenhead',
    name: 'Storia',
    headline: 'Decent Italian in Maidenhead',
    city: 'Maidenhead',
    neighbourhood: 'Town Centre',
    category: 'Italian',
    price: '$$',
    tags: ['italian', 'pasta', 'maidenhead'],
    defaultRating: 4.3,
    lat: 51.5234228,
    lng: -0.7155902,
  },
  {
    id: 'yauatcha-city-london',
    name: 'Yauatcha City',
    headline: 'Pretty dim sum, but pricey',
    city: 'London',
    neighbourhood: 'City of London',
    category: 'Chinese',
    price: '$$$$',
    tags: ['dim sum', 'pretty', 'pricey'],
    defaultRating: 4.6,
    lat: 51.5190098,
    lng: -0.0833532,
  },
  {
    id: 'jncquoi-asia-lisbon',
    name: 'JNcQUOI Asia',
    headline: 'Ambience is on point',
    city: 'Lisbon',
    neighbourhood: 'Chiado',
    category: 'Asian Fusion',
    price: '$$$$',
    tags: ['ambience', 'asian fusion', 'date spot'],
    defaultRating: 4.7,
    lat: 38.71964,
    lng: -9.14409,
  },
  {
    id: 'hemenways-providence',
    name: "Hemenway's Restaurant",
    headline: 'One of the freshest lobsters ever',
    city: 'Providence',
    neighbourhood: 'Downtown',
    category: 'Seafood',
    price: '$$$$',
    tags: ['lobster', 'seafood', 'fresh'],
    defaultRating: 4.5,
    lat: 41.8236,
    lng: -71.4102,
  },
  {
    id: 'gloria-osteria-milan',
    name: 'Gloria Osteria',
    headline: 'Great atmosphere, great Italian food',
    city: 'Milan',
    neighbourhood: 'Brera',
    category: 'Italian',
    price: '$$$',
    tags: ['italian', 'vibes', 'milan'],
    defaultRating: 4.5,
    lat: 45.4717878,
    lng: 9.1832399,
  },
  {
    id: 'charcoal-steak-house-waterloo',
    name: 'Charcoal Steak House',
    headline: 'Good steak',
    city: 'Kitchener',
    neighbourhood: 'King St',
    category: 'Steakhouse',
    price: '$$$',
    tags: ['steak', 'waterloo', 'classic'],
    defaultRating: 4.6,
    lat: 43.42908,
    lng: -80.43270,
  },
  {
    id: 'charcoal-kebab-house-toronto',
    name: 'Charcoal Kebab House',
    headline: 'Lamb skewers go crazy',
    city: 'Toronto',
    neighbourhood: 'TMU',
    category: 'Middle Eastern',
    price: '$',
    tags: ['kebab', 'lamb', 'skewers'],
    defaultRating: 4.6,
    lat: 43.65788,
    lng: -79.37599,
  },
  {
    id: 'daldongnae-waterloo',
    name: 'Daldongnae',
    headline: 'Best K-BBQ restaurant in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Korean',
    price: '$$',
    tags: ['kbbq', 'korean', 'best kbbq restaurant in waterloo'],
    defaultRating: 4.5,
    lat: 43.4665967,
    lng: -80.5229509,
  },
  {
    id: 'lancaster-smokehouse-kitchener',
    name: 'The Lancaster Smokehouse',
    headline: 'Big portions, tasty BBQ',
    city: 'Kitchener',
    neighbourhood: 'Bridgeport',
    category: 'BBQ',
    price: '$$',
    tags: ['bbq', 'ribs', 'big portions'],
    defaultRating: 4.6,
    lat: 43.47982,
    lng: -80.48426,
  },
  {
    id: 'osaka-reading',
    name: 'Osaka',
    headline: 'Best Japanese restaurant in Reading',
    city: 'Reading',
    neighbourhood: 'Town Centre',
    category: 'Japanese',
    price: '$$',
    tags: ['japanese', 'sushi', 'best japanese restaurant in reading'],
    defaultRating: 4.4,
    lat: 51.4531792,
    lng: -0.9715932,
  },
  {
    id: 'moxies-kitchener',
    name: 'Moxies',
    headline: 'Decent sports bar, good chicken burger',
    city: 'Kitchener',
    neighbourhood: 'Fairway',
    category: 'Bar & Grill',
    price: '$$',
    tags: ['sports bar', 'burgers', 'chicken burger'],
    defaultRating: 4.3,
    lat: 43.42085,
    lng: -80.44224,
  },
  {
    id: 'egg-club-waterloo',
    name: 'Egg Club',
    headline: 'Surprisingly good coffee',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Brunch',
    price: '$',
    tags: ['brunch', 'coffee', 'casual'],
    defaultRating: 4.4,
    lat: 43.478327,
    lng: -80.5248949,
  },
  {
    id: 'le-bistronome-caen',
    name: 'Le Bistronome',
    headline: 'Mussels go hard',
    city: 'Caen',
    neighbourhood: 'City Centre',
    category: 'French',
    price: '$$',
    tags: ['mussels', 'french', 'bistro'],
    defaultRating: 4.4,
    lat: 49.1845869,
    lng: -0.3564887,
  },
  {
    id: 'burger-and-lobster-soho',
    name: 'Burger & Lobster',
    headline: 'Fond memories, still hits',
    city: 'London',
    neighbourhood: 'Soho',
    category: 'Seafood',
    price: '$$$',
    tags: ['lobster', 'burgers', 'soho'],
    defaultRating: 4.5,
    lat: 51.5070258,
    lng: -0.1455603,
  },
  {
    id: 'le-select-bistro-toronto',
    name: 'Le Sélect Bistro',
    headline: 'The bacon is remarkable',
    city: 'Toronto',
    neighbourhood: 'King West',
    category: 'French',
    price: '$$$',
    tags: ['french', 'brunch', 'bacon'],
    defaultRating: 4.6,
    lat: 43.643826,
    lng: -79.3968131,
  },
  {
    id: 'bloom-lisbon',
    name: 'BLOOM',
    headline: 'Go-to brunch in Lisbon',
    city: 'Lisbon',
    neighbourhood: 'Chiado',
    category: 'Brunch',
    price: '$$',
    tags: ['brunch', 'lisbon', 'go-to'],
    defaultRating: 4.4,
    lat: 38.7471765,
    lng: -9.1802941,
  },
  {
    id: 'marugame-udon-london',
    name: 'Marugame Udon',
    headline: 'Only here for the curry udon',
    city: 'London',
    neighbourhood: 'Oxford Circus',
    category: 'Japanese',
    price: '$',
    tags: ['udon', 'curry udon', 'quick eats'],
    defaultRating: 4.3,
    lat: 51.5179884,
    lng: -0.0782322,
  },
  {
    id: 'ken-sushi-waterloo',
    name: 'KEN Sushi',
    headline: 'Very reasonably priced sushi',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Japanese',
    price: '$$',
    tags: ['sushi', 'budget', 'waterloo'],
    defaultRating: 4.4,
    lat: 43.473558,
    lng: -80.537141,
  },
  {
    id: 'asakusa-waterloo',
    name: 'Asakusa',
    headline: 'Favourite DoorDash ramen in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Japanese',
    price: '$$',
    tags: ['ramen', 'delivery', 'waterloo'],
    defaultRating: 4.3,
    lat: 43.4727923,
    lng: -80.5361247,
  },
  {
    id: 'seoul-soul-waterloo',
    name: 'Seoul Soul',
    headline: 'Huge portions of Korean fried chicken',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Korean',
    price: '$$',
    tags: ['korean', 'fried chicken', 'big portions'],
    defaultRating: 4.4,
    lat: 43.472339,
    lng: -80.5388973,
  },
  {
    id: 'the-botanist-uk',
    name: 'The Botanist',
    headline: 'Very good, nothing more to say',
    city: 'Reading',
    neighbourhood: 'Town Centre',
    category: 'British',
    price: '$$',
    tags: ['british', 'cocktails', 'solid'],
    defaultRating: 4.4,
    lat: 51.4552092,
    lng: -0.9695381,
  },
  {
    id: 'wildcraft-grill-waterloo',
    name: 'Wildcraft Grill and Long Bar',
    headline: 'Never disappoints',
    city: 'Waterloo',
    neighbourhood: 'Northfield',
    category: 'Steakhouse',
    price: '$$$',
    tags: ['steak', 'reliable', 'waterloo'],
    defaultRating: 4.6,
    lat: 43.48696,
    lng: -80.52672,
  },
  {
    id: 'quintal-das-docas-lisbon',
    name: 'Quintal das Docas',
    headline: 'Expensive but solid',
    city: 'Lisbon',
    neighbourhood: 'Doca de Santo Amaro',
    category: 'Portuguese',
    price: '$$$',
    tags: ['portuguese', 'seafood', 'dockside'],
    defaultRating: 4.2,
    lat: 38.7000516,
    lng: -9.1776637,
  },
  {
    id: 'stk-steakhouse-midtown-nyc',
    name: 'STK Steakhouse Midtown',
    headline: 'Holy expensive',
    city: 'New York',
    neighbourhood: 'Midtown',
    category: 'Steakhouse',
    price: '$$$$',
    tags: ['steak', 'expensive', 'nyc'],
    defaultRating: 4.2,
    lat: 40.75487,
    lng: -73.98258,
  },
  {
    id: 'er-hotpot-6th-ave-nyc',
    name: 'ER Hotpot',
    headline: 'Good vibes, nice hotpot',
    city: 'New York',
    neighbourhood: 'Midtown',
    category: 'Hotpot',
    price: '$$',
    tags: ['hotpot', 'vibes', 'nyc'],
    defaultRating: 4.3,
    lat: 40.75299,
    lng: -73.98581,
  },
  {
    id: 'red-8-everett',
    name: 'Red 8',
    headline: 'Funny casino restaurant with solid food',
    city: 'Everett',
    neighbourhood: 'Encore Boston Harbor',
    category: 'Asian Fusion',
    price: '$$$',
    tags: ['casino', 'asian fusion', 'dim sum'],
    defaultRating: 4.4,
    lat: 42.39552,
    lng: -71.07009,
  },
  {
    id: 'haidilao-toronto',
    name: 'Haidilao',
    headline: 'Noodle dances in Toronto',
    city: 'Toronto',
    neighbourhood: 'Downtown',
    category: 'Hotpot',
    price: '$$$',
    tags: ['hotpot', 'noodle dance', 'experience'],
    defaultRating: 4.3,
    lat: 43.8087474,
    lng: -79.2683143,
  },
  {
    id: 'the-keg-waterloo',
    name: 'The Keg',
    headline: 'Decent steak at a decent price',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Steakhouse',
    price: '$$$',
    tags: ['steak', 'chain', 'reliable'],
    defaultRating: 4.2,
    lat: 43.5031702,
    lng: -80.5303223,
  },
  {
    id: 'hakata-tonton-nyc',
    name: 'Hakata TonTon',
    headline: 'Creative but maybe too creative',
    city: 'New York',
    neighbourhood: 'Midtown',
    category: 'Japanese',
    price: '$$',
    tags: ['ramen', 'creative', 'nyc'],
    defaultRating: 4.2,
    lat: 40.7499004,
    lng: -73.985695,
  },
  {
    id: 'kabob-place-waterloo',
    name: 'Kabob Place',
    headline: 'Good Iranian food in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'University',
    category: 'Middle Eastern',
    price: '$$',
    tags: ['iranian', 'kebab', 'waterloo'],
    defaultRating: 4.1,
    lat: 43.47543,
    lng: -80.53573,
  },
  {
    id: 'songs-lamian-waterloo',
    name: "Song's Lamian",
    headline: 'Braised beef noodle soup hits',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Chinese',
    price: '$$',
    tags: ['lamian', 'noodles', 'waterloo'],
    defaultRating: 4.3,
    lat: 43.4664,
    lng: -80.5230,
  },
  {
    id: 'may-fair-kitchen-london',
    name: 'May Fair Kitchen',
    headline: 'Lots of lemon',
    city: 'London',
    neighbourhood: 'Mayfair',
    category: 'Japanese',
    price: '$$$$',
    tags: ['mediterranean', 'lemon', 'upscale'],
    defaultRating: 4.2,
    lat: 51.5079445,
    lng: -0.1442553,
  },
  {
    id: 'dia-restaurant-lounge-toronto',
    name: 'Dia Restaurant and Lounge',
    headline: 'Good breakfast for a hotel restaurant',
    city: 'Toronto',
    neighbourhood: 'Yorkville',
    category: 'Canadian',
    price: '$$$',
    tags: ['hotel dining', 'breakfast', 'hong kong'],
    defaultRating: 4.2,
    lat: 43.67223,
    lng: -79.37748,
  },
  {
    id: 'chez-ma-cousine-geneva',
    name: 'Chez Ma Cousine',
    headline: 'Rotisserie chicken hits the spot',
    city: 'Geneva',
    neighbourhood: 'Old Town',
    category: 'French',
    price: '$$',
    tags: ['rotisserie', 'chicken', 'casual'],
    defaultRating: 4.2,
    lat: 46.2007272,
    lng: 6.1491988,
  },
  {
    id: 'the-reading-room-uk',
    name: 'The Reading Room',
    headline: 'Pretentious but solid food',
    city: 'Reading',
    neighbourhood: 'Town Centre',
    category: 'British',
    price: '$$$',
    tags: ['british', 'fine dining', 'pretentious'],
    defaultRating: 4.1,
    lat: 51.45627,
    lng: -0.96740,
  },
  {
    id: 'fish-hut-waterloo',
    name: 'Fish Hut',
    headline: 'Best fish and chips restaurant in Waterloo',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'British',
    price: '$',
    tags: ['fish and chips', 'best fish and chips restaurant in waterloo'],
    defaultRating: 4.3,
    lat: 43.4181754,
    lng: -80.536146,
  },
  {
    id: 'masala-zone-piccadilly',
    name: 'Masala Zone',
    headline: 'Loved the butter chicken',
    city: 'London',
    neighbourhood: 'Piccadilly Circus',
    category: 'Indian',
    price: '$$',
    tags: ['indian', 'butter chicken', 'casual'],
    defaultRating: 4.2,
    lat: 51.5097541,
    lng: -0.134198,
  },
  {
    id: 'ivy-asia-chelsea',
    name: 'The Ivy Asia Chelsea',
    headline: 'Decent pan-Asian',
    city: 'London',
    neighbourhood: 'Chelsea',
    category: 'Asian Fusion',
    price: '$$$$',
    tags: ['pan-asian', 'vibes', 'chain'],
    defaultRating: 4.3,
    lat: 51.48718,
    lng: -0.16953,
  },
  {
    id: 'kinton-ramen-waterloo',
    name: 'Kinton Ramen',
    headline: 'It’s fine',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Japanese',
    price: '$$',
    tags: ['ramen', 'chain', 'waterloo'],
    defaultRating: 4.2,
    lat: 43.4658958,
    lng: -80.5227621,
  },
  {
    id: 'famoso-pizzeria-waterloo',
    name: 'Famoso Italian Pizzeria',
    headline: 'Good, nothing special',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Pizza',
    price: '$$',
    tags: ['pizza', 'chain', 'casual'],
    defaultRating: 4.1,
    lat: 43.46453,
    lng: -80.52216,
  },
  {
    id: 'thai-square-covent-garden',
    name: 'Thai Square',
    headline: 'Nice pad thai',
    city: 'London',
    neighbourhood: 'Covent Garden',
    category: 'Thai',
    price: '$$',
    tags: ['pad thai', 'thai', 'touristy'],
    defaultRating: 4.0,
    lat: 51.5114618,
    lng: -0.1181043,
  },
  {
    id: 'materia-pizzeria-milan',
    name: 'Materia Pizzeria',
    headline: 'Pizza is good',
    city: 'Milan',
    neighbourhood: 'Centro',
    category: 'Pizza',
    price: '$$',
    tags: ['pizza', 'milan', 'neapolitan'],
    defaultRating: 4.3,
    lat: 45.46048,
    lng: 9.18124,
  },
  {
    id: 'gols-lanzhou-noodles-waterloo',
    name: "Gol's Lanzhou Noodles",
    headline: 'Like a warm hug',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Chinese',
    price: '$',
    tags: ['noodles', 'comfort food', 'waterloo'],
    defaultRating: 4.2,
    lat: 43.4671,
    lng: -80.5238,
  },
  {
    id: 'mizu-waterloo',
    name: 'Mizu Restaurant',
    headline: 'Fried rice on point',
    city: 'Waterloo',
    neighbourhood: 'Uptown',
    category: 'Chinese',
    price: '$$',
    tags: ['fried rice', 'chinese', 'waterloo'],
    defaultRating: 4.1,
    lat: 43.4727489,
    lng: -80.5362427,
  },
  {
    id: 'scaddabush-square-one',
    name: 'Scaddabush',
    headline: 'It’s fine',
    city: 'Mississauga',
    neighbourhood: 'Square One',
    category: 'Italian',
    price: '$$',
    tags: ['italian', 'chain', 'square one'],
    defaultRating: 4.0,
    lat: 43.5933641,
    lng: -79.6486385,
  },
  {
    id: 'brown-donkatsu-waterloo',
    name: 'Brown Donkatsu',
    headline: 'Big portions',
    city: 'Waterloo',
    neighbourhood: 'University',
    category: 'Japanese',
    price: '$$',
    tags: ['donkatsu', 'big portions', 'waterloo'],
    defaultRating: 4.2,
    lat: 43.47256,
    lng: -80.53572,
  },
  {
    id: 'giggling-squid-bracknell',
    name: 'Giggling Squid',
    headline: 'Just okay',
    city: 'Bracknell',
    neighbourhood: 'Town Centre',
    category: 'Thai',
    price: '$$',
    tags: ['thai', 'chain', 'mid'],
    defaultRating: 3.5,
    lat: 51.41686,
    lng: -0.75110,
  },
  {
    id: 'maison-la-poterne-caen',
    name: 'Maison La Poterne',
    headline: 'Good mussels',
    city: 'Caen',
    neighbourhood: 'City Centre',
    category: 'French',
    price: '$$',
    tags: ['mussels', 'french', 'bistro'],
    defaultRating: 4.3,
    lat: 49.18582,
    lng: -0.35911,
  },
  {
    id: 'edna-vita-toronto',
    name: 'Edna + Vita',
    headline: 'Overpriced and mid',
    city: 'Toronto',
    neighbourhood: 'King West',
    category: 'Italian',
    price: '$$$$',
    tags: ['italian', 'overpriced', 'mid'],
    defaultRating: 3.3,
    lat: 43.64955,
    lng: -79.38217,
  },
  {
    id: 'ivy-windsor',
    name: 'The Ivy',
    headline: 'Pricey, eh',
    city: 'Windsor',
    neighbourhood: 'Town Centre',
    category: 'British',
    price: '$$$$',
    tags: ['british', 'chain', 'pricey'],
    defaultRating: 3.2,
    lat: 51.4828034,
    lng: -0.6081159,
  },
  {
    id: 'punch-toronto',
    name: 'PUNCH',
    headline: 'A middling interpretation of British-Indian fusion',
    city: 'Toronto',
    neighbourhood: 'Downtown',
    category: 'Indian',
    price: '$$$$',
    tags: ['indian', 'fusion', 'disappointing'],
    defaultRating: 2.8,
    lat: 43.64604,
    lng: -79.39076,
  },
  {
    id: 'red-lobster-toronto',
    name: 'Red Lobster',
    headline: 'Nice lobster',
    city: 'Toronto',
    neighbourhood: 'Downtown',
    category: 'Seafood',
    price: '$$',
    tags: ['lobster', 'chain', 'seafood'],
    defaultRating: 3.5,
    lat: 43.6561655,
    lng: -79.3836362,
  },
  {
    id: 'the-chase-toronto',
    name: 'The Chase',
    headline: 'Just fine',
    city: 'Toronto',
    neighbourhood: 'Financial District',
    category: 'Canadian',
    price: '$$$$',
    tags: ['canadian', 'upscale', 'meh'],
    defaultRating: 3.8,
    lat: 54.6593163,
    lng: -1.7142735,
  },
  {
    id: 'le-188-degree-hong-kong',
    name: 'Le 188° Restaurant & Lounge',
    headline: 'Decent',
    city: 'Hong Kong',
    neighbourhood: 'Victoria Peak',
    category: 'French',
    price: '$$$$',
    tags: ['view', 'hong kong', 'fine dining'],
    defaultRating: 3.6,
    lat: 22.28921,
    lng: 114.19181,
  },
]


